export const genres = [
  { name: 'bal' },
  { name: 'blues' },
  { name: 'bossa-nova' },
  { name: 'champeta' },
  { name: 'french song' },
  { name: 'folk' },
  { name: 'chilena' },
  { name: 'chipmusic' },
  { name: 'electro' },
  { name: 'classical' },
  { name: 'bluegrass' },
  { name: 'cumbia' },
  { name: 'dancehall' },
  { name: 'metal' },
  { name: 'disco' },
  { name: 'pop' },
  { name: 'rock' },
  { name: 'alternative rock' },
  { name: 'pop rock' },
  { name: 'indie rock' },
  { name: 'hard rock' },
  { name: 'fado' },
  { name: 'jazz' },
  { name: 'funk' },
  { name: 'gangsta rap' },
  { name: 'gnawa' },
  { name: 'gothic' },
  { name: 'grunge' },
  { name: 'house' },
  { name: 'irish' },
  { name: 'jamaican' },
  { name: 'japanese' },
  { name: 'jazz rock' },
  { name: 'north african' },
  { name: 'symphonic' },
  { name: 'opera' },
  { name: 'punk' },
  { name: 'rap' },
  { name: 'hip-hop' },
  { name: `r'n'b` },
  { name: `rock'n'roll` },
  { name: 'samba' },
  { name: 'ska' },
  { name: 'soul' },
  { name: 'tango' },
  { name: 'techno' },
].sort((a, b) => (a.name > b.name ? 1 : -1));
