import type { NextPage } from 'next';
import Head from 'next/head';
import { Footer } from '@components/Footer';

const Home: NextPage = () => (
  <div className="px-8">
    <Head>
      <title>Lyrichords</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className="flex min-h-[100vh] flex-1 flex-col items-center justify-center py-16">
      <h1 className="m-0 text-center text-6xl">Lyrichords</h1>

      <p className="my-16 text-center text-2xl">
        A simple app to gather your favorite songs&apos; lyrics.
      </p>
    </main>

    <Footer />
  </div>
);

export default Home;
