import type { NextPage } from 'next';
import Head from 'next/head';
import { Grid } from '@components/Grid';
import { Footer } from '@components/Footer';
import { CardLink } from '@components/CardLink';

const Home: NextPage = () => (
  <div className="px-8">
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className="flex min-h-[100vh] flex-1 flex-col items-center justify-center py-16">
      <h1 className="m-0 text-center text-6xl">
        Welcome to{' '}
        <a
          className="text-[#0070f3] hover:underline focus:underline active:underline"
          href="https://nextjs.org"
        >
          Next.js!
        </a>
      </h1>

      <p className="my-16 text-center text-2xl">
        Get started by editing <code className="code">pages/index.tsx</code>
      </p>

      <Grid>
        <CardLink href="https://nextjs.org/docs">
          <h2 className="mb-4 text-2xl font-semibold">Documentation &rarr;</h2>
          <p className="m-0 text-lg">
            Find in-depth information about Next.js features and API...
          </p>
        </CardLink>

        <CardLink href="https://nextjs.org/learn">
          <h2 className="mb-4 text-2xl font-semibold">Learn &rarr;</h2>
          <p className="m-0 text-lg">
            Learn about Next.js in an interactive course with quizzes!
          </p>
        </CardLink>

        <CardLink href="https://github.com/vercel/next.js/tree/canary/examples">
          <h2 className="mb-4 text-2xl font-semibold">Examples &rarr;</h2>
          <p className="m-0 text-lg">
            Discover and deploy boilerplate example Next.js projects.
          </p>
        </CardLink>

        <CardLink href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app">
          <h2 className="mb-4 text-2xl font-semibold">Deploy &rarr;</h2>
          <p className="m-0 text-lg">
            Instantly deploy your Next.js site to a public URL with Vercel.
          </p>
        </CardLink>
      </Grid>
    </main>

    <Footer />
  </div>
);

export default Home;
